import "@repo/ui/globals.css";
import { Noto_Sans_KR } from "next/font/google";
import Script from "next/script";
import React from "react";

import type { Metadata } from "next";

const inter = Noto_Sans_KR({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Docs",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <Script
        src="/widget/main.js"
        data-service="demo"
        data-theme="light"
        strategy="afterInteractive"
      />
    </html>
  );
}
